/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_Package;

/**
 *
 * @author Ankit Das
 */
import College_Project.*;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

public class Proctor_frame extends javax.swing.JFrame {

    /**
     * Creates new form Proctor_frame
     */
    Proctor p;
    
    public Proctor_frame(Proctor p1) {
        p = p1;
        initComponents();
        this.proctor_id.setText(p.proctorID);
        this.proctor_name.setText(p.ProctorName);
        
        String[] stud_usn = p.listStudents();
        this.usn.removeAllItems();
        for(String x:stud_usn) {
            this.usn.addItem(x);
        }
        
        this.studMarks.setEnabled(false);
        set_textfield_disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        add_stud = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        stud_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stud_usn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stud_dept = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stud_sem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        attendance = new javax.swing.JTextField();
        delete_stud = new java.awt.Button();
        update_stud = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        studMarks = new javax.swing.JTable();
        update_marks = new java.awt.Button();
        check = new java.awt.Button();
        logout = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        proctor_id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        proctor_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("proctor");
        setLocation(new java.awt.Point(550, 200));

        jPanel1.setBackground(new java.awt.Color(65, 105, 225));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proctor");

        usn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        usn.setOpaque(false);
        usn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usnItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student USN:");

        add_stud.setBackground(new java.awt.Color(29, 29, 184));
        add_stud.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        add_stud.setForeground(new java.awt.Color(255, 255, 255));
        add_stud.setLabel("Add Student");
        add_stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_studActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        stud_name.setBackground(new java.awt.Color(116, 145, 233));
        stud_name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        stud_name.setForeground(new java.awt.Color(234, 239, 252));
        stud_name.setCaretColor(new java.awt.Color(234, 239, 252));
        stud_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USN");

        stud_usn.setBackground(new java.awt.Color(116, 145, 233));
        stud_usn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        stud_usn.setForeground(new java.awt.Color(234, 239, 252));
        stud_usn.setCaretColor(new java.awt.Color(234, 239, 252));
        stud_usn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department");

        stud_dept.setBackground(new java.awt.Color(116, 145, 233));
        stud_dept.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        stud_dept.setForeground(new java.awt.Color(234, 239, 252));
        stud_dept.setCaretColor(new java.awt.Color(234, 239, 252));
        stud_dept.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semester");

        stud_sem.setBackground(new java.awt.Color(116, 145, 233));
        stud_sem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        stud_sem.setForeground(new java.awt.Color(234, 239, 252));
        stud_sem.setCaretColor(new java.awt.Color(234, 239, 252));
        stud_sem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Attendance");

        attendance.setBackground(new java.awt.Color(116, 145, 233));
        attendance.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        attendance.setForeground(new java.awt.Color(234, 239, 252));
        attendance.setCaretColor(new java.awt.Color(234, 239, 252));
        attendance.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        delete_stud.setBackground(new java.awt.Color(29, 29, 184));
        delete_stud.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        delete_stud.setForeground(new java.awt.Color(255, 255, 255));
        delete_stud.setLabel("Delete Student");
        delete_stud.setMinimumSize(new java.awt.Dimension(216, 43));
        delete_stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_studActionPerformed(evt);
            }
        });

        update_stud.setBackground(new java.awt.Color(29, 29, 184));
        update_stud.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        update_stud.setForeground(new java.awt.Color(255, 255, 255));
        update_stud.setLabel("Update Student");
        update_stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_studActionPerformed(evt);
            }
        });

        studMarks.setBackground(new java.awt.Color(65, 105, 225));
        studMarks.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        studMarks.setForeground(new java.awt.Color(255, 255, 255));
        studMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject 1", "Subject 2", "Subject 3", "Subject 4", "Subject 5"
            }
        ));
        studMarks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studMarks.setEditingColumn(1);
        studMarks.setEditingRow(1);
        studMarks.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(studMarks);

        update_marks.setBackground(new java.awt.Color(29, 29, 184));
        update_marks.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        update_marks.setForeground(new java.awt.Color(255, 255, 255));
        update_marks.setLabel("Update Marks");
        update_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_marksActionPerformed(evt);
            }
        });

        check.setBackground(new java.awt.Color(29, 29, 184));
        check.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setLabel("Check Eligibility");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(29, 29, 184));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setLabel("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Proctor ID:");

        proctor_id.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        proctor_id.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Proctor Name:");

        proctor_name.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        proctor_name.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(27, 27, 27))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(33, 33, 33)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(59, 59, 59)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stud_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(stud_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(96, 96, 96)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stud_usn, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stud_name, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_stud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_stud, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(proctor_id, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(add_stud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(207, 207, 207)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(proctor_name, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(usn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(23, 23, 23))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(update_marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proctor_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(proctor_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_stud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usn)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_usn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stud_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(update_stud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stud_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(delete_stud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(update_marks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void set_textfield_disable() {
        this.stud_name.setEditable(false);
        this.stud_usn.setEditable(false);
        this.stud_dept.setEditable(false);
        this.stud_sem.setEditable(false);
        this.attendance.setEditable(false);
    }
    
    private void set_disable() {
        this.add_stud.disable();
        this.check.disable();
        this.delete_stud.disable();
        this.update_stud.disable();
        this.update_marks.disable();
        this.usn.disable();
    }
    
    private void set_textfield_enable() {
        this.stud_name.setEditable(true);
        this.stud_usn.setEditable(true);
        this.stud_dept.setEditable(true);
        this.stud_sem.setEditable(true);
        this.attendance.setEditable(true);
    }
    
    private void set_enable() {
        this.add_stud.enable();
        this.check.enable();
        this.delete_stud.enable();
        this.update_stud.enable();
        this.update_marks.enable();
        this.usn.enable();
    }
    
    
    private void add_studActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_studActionPerformed
        // TODO add your handling code here:
        set_disable();
        this.add_stud.setEnabled(true);
        
        
        if(this.add_stud.getLabel().equals("Add")) {
            
            p.studName = this.stud_name.getText();
            p.usn = this.stud_usn.getText();
            p.dept = this.stud_dept.getText();
            p.sem = Integer.parseInt(this.stud_sem.getText());
            p.attendance = Integer.parseInt(this.attendance.getText());
            
            p.addStud();
            JOptionPane.showMessageDialog(this, "Student added succefully");
            
            set_textfield_disable();
            this.add_stud.setLabel("Add Student");
            set_enable();
        }
        else {
            this.add_stud.setLabel("Add");
            set_textfield_enable();
        }
            
        
        String[] stud_usn = p.listStudents();
        this.usn.removeAllItems();
        for(String x:stud_usn) {
            this.usn.addItem(x);
        }
    }//GEN-LAST:event_add_studActionPerformed

    private void delete_studActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_studActionPerformed
        // TODO add your handling code here:
        p.delStud();
        JOptionPane.showMessageDialog(this, "Student deleted succefully");
        
        this.stud_name.setText("");
        this.stud_usn.setText("");
        this.stud_dept.setText("");
        this.stud_sem.setText("");
        this.attendance.setText("");
        
        for(int i=0; i<5; i=i+2) {
            this.studMarks.setValueAt("", 0, i/2);
            this.studMarks.setValueAt("", 1, i/2);
        }
        
        String[] stud_usn = p.listStudents();
        this.usn.removeAllItems();
        for(String x:stud_usn) {
            this.usn.addItem(x);
        }
    }//GEN-LAST:event_delete_studActionPerformed

    private void update_studActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_studActionPerformed
        // TODO add your handling code here:
        int index = 0;
        set_disable();
        this.update_stud.setEnabled(true);
        
        if(this.update_stud.getLabel().equals("Update")) {
            index = this.usn.getSelectedIndex();
            
            p.studName = this.stud_name.getText();
            p.usn = this.stud_usn.getText();
            p.dept = this.stud_dept.getText();
            p.sem = Integer.parseInt(this.stud_sem.getText());
            p.attendance = Integer.parseInt(this.attendance.getText());
        
            p.update(p.usn);
            JOptionPane.showMessageDialog(this, "Student updated succefully");
            
            set_textfield_disable();
            this.update_stud.setLabel("Update Student");
            set_enable();
            
            String[] stud_usn = p.listStudents();
            this.usn.removeAllItems();
            for(String x:stud_usn) {
            this.usn.addItem(x);
            }
            
            this.usn.setSelectedIndex(index);
        }
        else {
            this.update_stud.setLabel("Update");
            set_textfield_enable();
            this.stud_usn.setEditable(false);
        }
    }//GEN-LAST:event_update_studActionPerformed

    private void update_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_marksActionPerformed
        // TODO add your handling code here:
        set_disable();
        this.update_marks.setEnabled(true);
        
        
        if(this.update_marks.getLabel().equals("Update")) {
            int[] marks = new int[5];
            for(int i=0; i<5; i++) {
                String m = String.valueOf(studMarks.getValueAt(1, i));
                System.out.println(m + " ");
                marks[i] = Integer.parseInt(m);
            }
            p.updateMarks(marks);
            JOptionPane.showMessageDialog(this, "Marks update succefully");
            
            String[] sub = p.displayMarks(p.usn, p.dept, p.sem);
                for(int i=0; i<sub.length; i=i+2) {
                    System.out.println(sub[i] + " 0 " + i);
                    System.out.println(sub[i+1] + " 1 " + i);
                    this.studMarks.setValueAt(sub[i], 0, i/2);
                    this.studMarks.setValueAt(sub[i+1], 1, i/2);
            }
            
            this.update_marks.setLabel("Update Marks");
            this.studMarks.setEnabled(false);
            set_enable();
        }
        else {
            this.update_marks.setLabel("Update");
            this.studMarks.setEnabled(true);
        }

    }//GEN-LAST:event_update_marksActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        int atend = Integer.parseInt(this.attendance.getText());
        double percent = (double) atend / 1.2 ;
        if (percent < 80)
        JOptionPane.showMessageDialog(this, "Student " + p.studName +" is not eligible to write the Semester End Exmination");
        else
        JOptionPane.showMessageDialog(this, "Student " + p.studName +" is eligible to write the Semester End Exmination");
    }//GEN-LAST:event_checkActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int logout_confirm = JOptionPane.showConfirmDialog(this, "Do you really want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        
        if(logout_confirm == 0) {
            login lin = new login();
            lin.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_logoutActionPerformed

    private void usnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usnItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String selected_usn = usn.getSelectedItem().toString();
            p.usn = selected_usn;
            p.getDetails();
            
            this.stud_usn.setText(p.usn);
            this.stud_name.setText(p.studName);
            this.stud_dept.setText(p.dept);
            this.stud_sem.setText(p.sem + "");
            this.attendance.setText(p.attendance + "");
            
            String[] sub = p.displayMarks(p.usn, p.dept, p.sem);
            if(sub != null) 
                for(int i=0; i<sub.length; i=i+2) {
                    System.out.println(sub[i] + " 0 " + i);
                    System.out.println(sub[i+1] + " 1 " + i);
                    this.studMarks.setValueAt(sub[i], 0, i/2);
                    this.studMarks.setValueAt(sub[i+1], 1, i/2);
                }
            
            
            this.update_stud.setVisible(true);
            this.delete_stud.setVisible(true);
        }
    }//GEN-LAST:event_usnItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Proctor_frame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button add_stud;
    private javax.swing.JTextField attendance;
    private java.awt.Button check;
    private java.awt.Button delete_stud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Button logout;
    private javax.swing.JLabel proctor_id;
    private javax.swing.JLabel proctor_name;
    private javax.swing.JTable studMarks;
    private javax.swing.JTextField stud_dept;
    private javax.swing.JTextField stud_name;
    private javax.swing.JTextField stud_sem;
    private javax.swing.JTextField stud_usn;
    private java.awt.Button update_marks;
    private java.awt.Button update_stud;
    private javax.swing.JComboBox<String> usn;
    // End of variables declaration//GEN-END:variables
}
