/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_Package;

import College_Project.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Ankit Das
 */
public class Student_frame extends javax.swing.JFrame {

    /**
     * Creates new form Student_frame
     */
    Student s;
    
    public Student_frame(Student s1) {
        s = s1;
        initComponents();
        
        this.name.setText(s.studName);
        this.name.setEditable(false);
        this.usn.setText(s.usn);
        this.usn.setEditable(false);
        this.branch.setText(s.branch);
        this.branch.setEditable(false);
        this.sem.setText(s.sem + "");
        this.sem.setEditable(false);
        this.attendance.setText(s.attendance + "");
        this.attendance.setEditable(false);
        
        System.out.println();
        
        String[] sub = s.displayMarks(s.usn, s.branch, s.sem);
        for(int i=0; i<sub.length; i=i+2) {
            System.out.println(sub[i] + " 0 " + i);
            System.out.println(sub[i+1] + " 1 " + i);
            this.studMarks.setValueAt(sub[i], 0, i/2);
            this.studMarks.setValueAt(sub[i+1], 1, i/2);
        }
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        branch = new javax.swing.JTextField();
        sem = new javax.swing.JTextField();
        update_sem = new javax.swing.JLabel();
        update_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        attendance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studMarks = new javax.swing.JTable();
        check = new java.awt.Button();
        logout = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");
        setLocation(new java.awt.Point(550, 200));

        jPanel1.setBackground(new java.awt.Color(65, 105, 225));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        name.setBackground(new java.awt.Color(116, 145, 233));
        name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(234, 239, 252));
        name.setCaretColor(new java.awt.Color(234, 239, 252));
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USN");

        usn.setBackground(new java.awt.Color(116, 145, 233));
        usn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        usn.setForeground(new java.awt.Color(234, 239, 252));
        usn.setCaretColor(new java.awt.Color(234, 239, 252));
        usn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semester");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department");

        branch.setBackground(new java.awt.Color(116, 145, 233));
        branch.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        branch.setForeground(new java.awt.Color(234, 239, 252));
        branch.setCaretColor(new java.awt.Color(234, 239, 252));
        branch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        sem.setBackground(new java.awt.Color(116, 145, 233));
        sem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sem.setForeground(new java.awt.Color(234, 239, 252));
        sem.setCaretColor(new java.awt.Color(234, 239, 252));
        sem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        update_sem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        update_sem.setForeground(new java.awt.Color(255, 154, 154));
        update_sem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_sem.setText("Update");
        update_sem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_semMouseClicked(evt);
            }
        });

        update_name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        update_name.setForeground(new java.awt.Color(255, 154, 154));
        update_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_name.setText("Update");
        update_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_nameMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Attendance");

        attendance.setBackground(new java.awt.Color(116, 145, 233));
        attendance.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        attendance.setForeground(new java.awt.Color(234, 239, 252));
        attendance.setCaretColor(new java.awt.Color(234, 239, 252));
        attendance.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        studMarks.setBackground(new java.awt.Color(65, 105, 225));
        studMarks.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        studMarks.setForeground(new java.awt.Color(255, 255, 255));
        studMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject 1", "Subject 2", "Subject 3", "Subject 4", "Subject 5"
            }
        ));
        studMarks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studMarks.setEditingColumn(1);
        studMarks.setEditingRow(1);
        studMarks.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(studMarks);

        check.setBackground(new java.awt.Color(29, 29, 184));
        check.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setLabel("Check Eligibility");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(29, 29, 184));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setLabel("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(branch)
                                    .addComponent(sem)
                                    .addComponent(attendance)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(96, 96, 96)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(usn))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_sem)
                            .addComponent(update_name))
                        .addGap(190, 190, 190))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_name))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update_sem)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_semMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_semMouseClicked
        // TODO add your handling code here:
        String sem = JOptionPane.showInputDialog(this, "Enter Semester:");
        s.update(2, sem);
        this.sem.setText(sem);
    }//GEN-LAST:event_update_semMouseClicked

    private void update_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_nameMouseClicked
        // TODO add your handling code here:
        String stud_name = JOptionPane.showInputDialog(this, "Enter Name:");
        s.update(1, stud_name);
        this.name.setText(stud_name);
    }//GEN-LAST:event_update_nameMouseClicked

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        int atend = Integer.parseInt(this.attendance.getText());
        double percent = (double) atend / 1.2 ;
        if (percent < 80)
            JOptionPane.showMessageDialog(this, "You're not eligible to write the Semester End Exmination");
        else
            JOptionPane.showMessageDialog(this, "You're eligible to write the Semester End Exmination");
    }//GEN-LAST:event_checkActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int logout_confirm = JOptionPane.showConfirmDialog(this, "Do you really want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        
        if(logout_confirm == 0) {
            login lin = new login();
            lin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Student_frame(Student s).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attendance;
    private javax.swing.JTextField branch;
    private java.awt.Button check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Button logout;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sem;
    private javax.swing.JTable studMarks;
    private javax.swing.JLabel update_name;
    private javax.swing.JLabel update_sem;
    private javax.swing.JTextField usn;
    // End of variables declaration//GEN-END:variables
}
